// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0--rc2
// source: internal/controller/grpc/v1/log.proto

package loggrpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_INFO                  LogLevel = 1
	LogLevel_WARN                  LogLevel = 2
	LogLevel_ERROR                 LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "INFO",
		2: "WARN",
		3: "ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"INFO":                  1,
		"WARN":                  2,
		"ERROR":                 3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_controller_grpc_v1_log_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_internal_controller_grpc_v1_log_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_internal_controller_grpc_v1_log_proto_rawDescGZIP(), []int{0}
}

type SendStatus int32

const (
	SendStatus_STATUS_OK     SendStatus = 0
	SendStatus_STATUS_FAILED SendStatus = 1
)

// Enum value maps for SendStatus.
var (
	SendStatus_name = map[int32]string{
		0: "STATUS_OK",
		1: "STATUS_FAILED",
	}
	SendStatus_value = map[string]int32{
		"STATUS_OK":     0,
		"STATUS_FAILED": 1,
	}
)

func (x SendStatus) Enum() *SendStatus {
	p := new(SendStatus)
	*p = x
	return p
}

func (x SendStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_controller_grpc_v1_log_proto_enumTypes[1].Descriptor()
}

func (SendStatus) Type() protoreflect.EnumType {
	return &file_internal_controller_grpc_v1_log_proto_enumTypes[1]
}

func (x SendStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendStatus.Descriptor instead.
func (SendStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_controller_grpc_v1_log_proto_rawDescGZIP(), []int{1}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=log.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_internal_controller_grpc_v1_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_grpc_v1_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_internal_controller_grpc_v1_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SendLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         string                 `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Status        SendStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=log.SendStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogResponse) Reset() {
	*x = SendLogResponse{}
	mi := &file_internal_controller_grpc_v1_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogResponse) ProtoMessage() {}

func (x *SendLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controller_grpc_v1_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogResponse.ProtoReflect.Descriptor instead.
func (*SendLogResponse) Descriptor() ([]byte, []int) {
	return file_internal_controller_grpc_v1_log_proto_rawDescGZIP(), []int{1}
}

func (x *SendLogResponse) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *SendLogResponse) GetStatus() SendStatus {
	if x != nil {
		return x.Status
	}
	return SendStatus_STATUS_OK
}

var File_internal_controller_grpc_v1_log_proto protoreflect.FileDescriptor

const file_internal_controller_grpc_v1_log_proto_rawDesc = "" +
	"\n" +
	"%internal/controller/grpc/v1/log.proto\x12\x03log\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x01\n" +
	"\bLogEntry\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12#\n" +
	"\x05level\x18\x02 \x01(\x0e2\r.log.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"Q\n" +
	"\x0fSendLogResponse\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\tR\x05logId\x12'\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0f.log.SendStatusR\x06status*D\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\b\n" +
	"\x04WARN\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03*.\n" +
	"\n" +
	"SendStatus\x12\r\n" +
	"\tSTATUS_OK\x10\x00\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x012<\n" +
	"\n" +
	"LogService\x12.\n" +
	"\aSendLog\x12\r.log.LogEntry\x1a\x14.log.SendLogResponseB\tZ\a/gen;v1b\x06proto3"

var (
	file_internal_controller_grpc_v1_log_proto_rawDescOnce sync.Once
	file_internal_controller_grpc_v1_log_proto_rawDescData []byte
)

func file_internal_controller_grpc_v1_log_proto_rawDescGZIP() []byte {
	file_internal_controller_grpc_v1_log_proto_rawDescOnce.Do(func() {
		file_internal_controller_grpc_v1_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_controller_grpc_v1_log_proto_rawDesc), len(file_internal_controller_grpc_v1_log_proto_rawDesc)))
	})
	return file_internal_controller_grpc_v1_log_proto_rawDescData
}

var file_internal_controller_grpc_v1_log_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_controller_grpc_v1_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_controller_grpc_v1_log_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: log.LogLevel
	(SendStatus)(0),               // 1: log.SendStatus
	(*LogEntry)(nil),              // 2: log.LogEntry
	(*SendLogResponse)(nil),       // 3: log.SendLogResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_internal_controller_grpc_v1_log_proto_depIdxs = []int32{
	0, // 0: log.LogEntry.level:type_name -> log.LogLevel
	4, // 1: log.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: log.SendLogResponse.status:type_name -> log.SendStatus
	2, // 3: log.LogService.SendLog:input_type -> log.LogEntry
	3, // 4: log.LogService.SendLog:output_type -> log.SendLogResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_controller_grpc_v1_log_proto_init() }
func file_internal_controller_grpc_v1_log_proto_init() {
	if File_internal_controller_grpc_v1_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_controller_grpc_v1_log_proto_rawDesc), len(file_internal_controller_grpc_v1_log_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_controller_grpc_v1_log_proto_goTypes,
		DependencyIndexes: file_internal_controller_grpc_v1_log_proto_depIdxs,
		EnumInfos:         file_internal_controller_grpc_v1_log_proto_enumTypes,
		MessageInfos:      file_internal_controller_grpc_v1_log_proto_msgTypes,
	}.Build()
	File_internal_controller_grpc_v1_log_proto = out.File
	file_internal_controller_grpc_v1_log_proto_goTypes = nil
	file_internal_controller_grpc_v1_log_proto_depIdxs = nil
}
