// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0--rc2
// source: api/log/v1/log_service.proto

package loggrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_INFO                  LogLevel = 1
	LogLevel_WARN                  LogLevel = 2
	LogLevel_ERROR                 LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "INFO",
		2: "WARN",
		3: "ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"INFO":                  1,
		"WARN":                  2,
		"ERROR":                 3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_log_v1_log_service_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_api_log_v1_log_service_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_log_v1_log_service_proto_rawDescGZIP(), []int{0}
}

type SendStatus int32

const (
	SendStatus_STATUS_OK     SendStatus = 0
	SendStatus_STATUS_FAILED SendStatus = 1
)

// Enum value maps for SendStatus.
var (
	SendStatus_name = map[int32]string{
		0: "STATUS_OK",
		1: "STATUS_FAILED",
	}
	SendStatus_value = map[string]int32{
		"STATUS_OK":     0,
		"STATUS_FAILED": 1,
	}
)

func (x SendStatus) Enum() *SendStatus {
	p := new(SendStatus)
	*p = x
	return p
}

func (x SendStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_log_v1_log_service_proto_enumTypes[1].Descriptor()
}

func (SendStatus) Type() protoreflect.EnumType {
	return &file_api_log_v1_log_service_proto_enumTypes[1]
}

func (x SendStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendStatus.Descriptor instead.
func (SendStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_log_v1_log_service_proto_rawDescGZIP(), []int{1}
}

type SendLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=log.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogRequest) Reset() {
	*x = SendLogRequest{}
	mi := &file_api_log_v1_log_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogRequest) ProtoMessage() {}

func (x *SendLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogRequest.ProtoReflect.Descriptor instead.
func (*SendLogRequest) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendLogRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SendLogRequest) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *SendLogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendLogRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SendLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         string                 `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Status        SendStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=log.SendStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogResponse) Reset() {
	*x = SendLogResponse{}
	mi := &file_api_log_v1_log_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogResponse) ProtoMessage() {}

func (x *SendLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogResponse.ProtoReflect.Descriptor instead.
func (*SendLogResponse) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendLogResponse) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *SendLogResponse) GetStatus() SendStatus {
	if x != nil {
		return x.Status
	}
	return SendStatus_STATUS_OK
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=log.LogLevel" json:"level,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_api_log_v1_log_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLogsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetLogsRequest) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *GetLogsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetLogsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*SendLogRequest      `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_api_log_v1_log_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetLogsResponse) GetLogs() []*SendLogRequest {
	if x != nil {
		return x.Logs
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_log_v1_log_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetStatsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetStatsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type LogLevelCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=log.LogLevel" json:"level,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelCount) Reset() {
	*x = LogLevelCount{}
	mi := &file_api_log_v1_log_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelCount) ProtoMessage() {}

func (x *LogLevelCount) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelCount.ProtoReflect.Descriptor instead.
func (*LogLevelCount) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_service_proto_rawDescGZIP(), []int{5}
}

func (x *LogLevelCount) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogLevelCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalLogs     int32                  `protobuf:"varint,1,opt,name=total_logs,json=totalLogs,proto3" json:"total_logs,omitempty"`
	LogsByLevel   []*LogLevelCount       `protobuf:"bytes,3,rep,name=logs_by_level,json=logsByLevel,proto3" json:"logs_by_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_api_log_v1_log_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_log_v1_log_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_log_v1_log_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatsResponse) GetTotalLogs() int32 {
	if x != nil {
		return x.TotalLogs
	}
	return 0
}

func (x *GetStatsResponse) GetLogsByLevel() []*LogLevelCount {
	if x != nil {
		return x.LogsByLevel
	}
	return nil
}

var File_api_log_v1_log_service_proto protoreflect.FileDescriptor

const file_api_log_v1_log_service_proto_rawDesc = "" +
	"\n" +
	"\x1capi/log/v1/log_service.proto\x12\x03log\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\x0eSendLogRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12#\n" +
	"\x05level\x18\x02 \x01(\x0e2\r.log.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"Q\n" +
	"\x0fSendLogResponse\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\tR\x05logId\x12'\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0f.log.SendStatusR\x06status\"\xc1\x01\n" +
	"\x0eGetLogsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12#\n" +
	"\x05level\x18\x02 \x01(\x0e2\r.log.LogLevelR\x05level\x12.\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\":\n" +
	"\x0fGetLogsResponse\x12'\n" +
	"\x04logs\x18\x01 \x03(\v2\x13.log.SendLogRequestR\x04logs\"\x87\x01\n" +
	"\x0fGetStatsRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"J\n" +
	"\rLogLevelCount\x12#\n" +
	"\x05level\x18\x01 \x01(\x0e2\r.log.LogLevelR\x05level\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"i\n" +
	"\x10GetStatsResponse\x12\x1d\n" +
	"\n" +
	"total_logs\x18\x01 \x01(\x05R\ttotalLogs\x126\n" +
	"\rlogs_by_level\x18\x03 \x03(\v2\x12.log.LogLevelCountR\vlogsByLevel*D\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\b\n" +
	"\x04WARN\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03*.\n" +
	"\n" +
	"SendStatus\x12\r\n" +
	"\tSTATUS_OK\x10\x00\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x012\xb1\x01\n" +
	"\n" +
	"LogService\x124\n" +
	"\aSendLog\x12\x13.log.SendLogRequest\x1a\x14.log.SendLogResponse\x124\n" +
	"\aGetLogs\x12\x13.log.GetLogsRequest\x1a\x14.log.GetLogsResponse\x127\n" +
	"\bGetStats\x12\x14.log.GetStatsRequest\x1a\x15.log.GetStatsResponseB\x16Z\x14/loggrpc_gen;loggrpcb\x06proto3"

var (
	file_api_log_v1_log_service_proto_rawDescOnce sync.Once
	file_api_log_v1_log_service_proto_rawDescData []byte
)

func file_api_log_v1_log_service_proto_rawDescGZIP() []byte {
	file_api_log_v1_log_service_proto_rawDescOnce.Do(func() {
		file_api_log_v1_log_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_log_v1_log_service_proto_rawDesc), len(file_api_log_v1_log_service_proto_rawDesc)))
	})
	return file_api_log_v1_log_service_proto_rawDescData
}

var file_api_log_v1_log_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_log_v1_log_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_log_v1_log_service_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: log.LogLevel
	(SendStatus)(0),               // 1: log.SendStatus
	(*SendLogRequest)(nil),        // 2: log.SendLogRequest
	(*SendLogResponse)(nil),       // 3: log.SendLogResponse
	(*GetLogsRequest)(nil),        // 4: log.GetLogsRequest
	(*GetLogsResponse)(nil),       // 5: log.GetLogsResponse
	(*GetStatsRequest)(nil),       // 6: log.GetStatsRequest
	(*LogLevelCount)(nil),         // 7: log.LogLevelCount
	(*GetStatsResponse)(nil),      // 8: log.GetStatsResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_api_log_v1_log_service_proto_depIdxs = []int32{
	0,  // 0: log.SendLogRequest.level:type_name -> log.LogLevel
	9,  // 1: log.SendLogRequest.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 2: log.SendLogResponse.status:type_name -> log.SendStatus
	0,  // 3: log.GetLogsRequest.level:type_name -> log.LogLevel
	9,  // 4: log.GetLogsRequest.from:type_name -> google.protobuf.Timestamp
	9,  // 5: log.GetLogsRequest.to:type_name -> google.protobuf.Timestamp
	2,  // 6: log.GetLogsResponse.logs:type_name -> log.SendLogRequest
	9,  // 7: log.GetStatsRequest.from:type_name -> google.protobuf.Timestamp
	9,  // 8: log.GetStatsRequest.to:type_name -> google.protobuf.Timestamp
	0,  // 9: log.LogLevelCount.level:type_name -> log.LogLevel
	7,  // 10: log.GetStatsResponse.logs_by_level:type_name -> log.LogLevelCount
	2,  // 11: log.LogService.SendLog:input_type -> log.SendLogRequest
	4,  // 12: log.LogService.GetLogs:input_type -> log.GetLogsRequest
	6,  // 13: log.LogService.GetStats:input_type -> log.GetStatsRequest
	3,  // 14: log.LogService.SendLog:output_type -> log.SendLogResponse
	5,  // 15: log.LogService.GetLogs:output_type -> log.GetLogsResponse
	8,  // 16: log.LogService.GetStats:output_type -> log.GetStatsResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_log_v1_log_service_proto_init() }
func file_api_log_v1_log_service_proto_init() {
	if File_api_log_v1_log_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_log_v1_log_service_proto_rawDesc), len(file_api_log_v1_log_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_log_v1_log_service_proto_goTypes,
		DependencyIndexes: file_api_log_v1_log_service_proto_depIdxs,
		EnumInfos:         file_api_log_v1_log_service_proto_enumTypes,
		MessageInfos:      file_api_log_v1_log_service_proto_msgTypes,
	}.Build()
	File_api_log_v1_log_service_proto = out.File
	file_api_log_v1_log_service_proto_goTypes = nil
	file_api_log_v1_log_service_proto_depIdxs = nil
}
